name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: db_mahasiswa
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ""
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=30s
          --health-timeout=5s
          --health-retries=3
      
      sonarqube:
        image: sonarqube:latest
        ports:
          - 9000:9000
        options: >-
          --health-cmd="curl -f http://localhost:9000/api/system/health || exit 1"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=10

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Wait for SonarQube to be ready
      run: |
        echo "Waiting for SonarQube to start..."
        until curl -s http://localhost:9000/api/system/status | grep -q '"status":"UP"'; do
          echo "SonarQube is not up yet. Waiting..."
          sleep 10
        done
        echo "SonarQube is up and running!"

    - name: Build and test with Maven
      run: mvn clean install --file pom.xml

    - name: Build package
      run: mvn package

    - name: Run Maven Build with SonarQube Analysis
      run: mvn sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.login=sqp_17f8514284fe42ffc3c1b82982afcbb0a33e25d1
